### ISSUE TITLE
EPIC: Build out UI for Projects page

### ISSUE THREAD

**Issue by lululeon** [colabco/cbld-web#6]
This epic will iteratively build out the frontend-UI for the cobuilders Project page, following the rough guideline of this mockup:

![image](https://github.com/colabco/cbld-api/assets/6601801/61bfdae6-2b0f-4dcc-b1df-320143e4ee40)

For this epic, no actual interactive functionality is needed unless specified on the ticket. We are just building out the visual design in a responsive (incl.  mobile-friendly) manner.

### Child Tickets
- [ ] Build out navbar UI
- [ ] Build out project description box
- [ ] Build out project details box
- [ ] Build out open roles box
- [ ] Build out the filter tasks box
